const characterName = 'name'
const avatar = 'image'
const attributes = {
  global_skills_mod: '',
  init_tiebreaker: '',
  initiative_bonus: '',
  version: '',
  global_skill_mod: '',
  global_save_mod: '',
  global_attack_mod: '',
  global_damage_mod_roll: '',
  global_damage_mod_crit: '',
  global_damage_mod_type: '',
  class: '',
  hitdietype: '',
  powercasting_ability: '',
  strength_save_prof: 'abilityScores.Strength.savingThrow.proficiency ? (@{pb}) : 0',
  dexterity_save_prof: 'abilityScores.Dexterity.savingThrow.proficiency ? (@{pb}) : 0',
  constitution_save_prof: 'abilityScores.Constitution.savingThrow.proficiency ? (@{pb}) : 0',
  intelligence_save_prof: 'abilityScores.Intelligence.savingThrow.proficiency ? (@{pb}) : 0',
  wisdom_save_prof: 'abilityScores.Wisdom.savingThrow.proficiency ? (@{pb}) : 0',
  charisma_save_prof: 'abilityScores.Charisma.savingThrow.proficiency ? (@{pb}) : 0',
  // class_resource_name: '',
  hitdie_final: '',
  level: 'currentLevel',
  caster_level: '',
  class_display: '',
  hit_dice: '',
  lvl1_slots_total: '',
  lvl2_slots_total: '',
  lvl3_slots_total: '',
  lvl4_slots_total: '',
  lvl5_slots_total: '',
  lvl6_slots_total: '',
  lvl7_slots_total: '',
  lvl8_slots_total: '',
  lvl9_slots_total: '',
  pb: '',
  jack: '',
  pbd_safe: '',
  jack_bonus: '',
  jack_attr: '',
  // strength_save_bonus: 'abilityScores.Strength.savingThrow.modifier',
  // dexterity_save_bonus: 'abilityScores.Dexterity.savingThrow.modifier',
  // constitution_save_bonus: 'abilityScores.Constitution.savingThrow.modifier',
  // intelligence_save_bonus: 'abilityScores.Intelligence.savingThrow.modifier',
  // wisdom_save_bonus: 'abilityScores.Wisdom.savingThrow.modifier',
  // charisma_save_bonus: 'abilityScores.Charisma.savingThrow.modifier',
  death_save_bonus: '',
  athletics_bonus: '',
  acrobatics_bonus: '',
  sleight_of_hand_bonus: '',
  stealth_bonus: '',
  technology_bonus: '',
  lore_bonus: '',
  investigation_bonus: '',
  nature_bonus: '',
  piloting_bonus: '',
  animal_handling_bonus: '',
  insight_bonus: '',
  medicine_bonus: '',
  perception_bonus: '',
  survival_bonus: '',
  deception_bonus: '',
  intimidation_bonus: '',
  performance_bonus: '',
  persuasion_bonus: '',
  power_attack_mod: '',
  power_attack_bonus: '',
  power_save_dc: '',
  passive_wisdom: '',
  subclass: '',
  base_level: '',
  race: 'species',
  // race_display: 'species',
  strength_base: 'abilityScores.Strength.value',
  // strength_flag: 0,
  // strength: '',
  // strength_mod: '',
  npc_str_negative: '',
  weighttotal: '',
  encumberance: '',
  hiddenweighttotal: '',
  dexterity_base: '',
  dexterity_flag: '',
  dexterity: '',
  dexterity_mod: '',
  npc_dex_negative: '',
  armorwarningflag: '',
  armorwarning: '',
  ac: '',
  constitution_base: '',
  constitution_flag: '',
  constitution: '',
  constitution_mod: '',
  npc_con_negative: '',
  intelligence_base: '',
  intelligence_flag: '',
  intelligence: '',
  intelligence_mod: '',
  npc_int_negative: '',
  wisdom_base: '',
  wisdom_flag: '',
  wisdom: '',
  wisdom_mod: '',
  npc_wis_negative: '',
  charisma_base: '',
  charisma_flag: '',
  charisma: '',
  charisma_mod: '',
  npc_cha_negative: '',
  lore_prof: '',
  perception_prof: '',
  insight_prof: '',
  performance_prof: '',
  deception_prof: '',
  speed: '',
  hp: '',
  ship_shield: '',
  personality_traits: '',
  ideals: '',
  bonds: '',
  flaws: '',
  tab: '',
  force_power_points_total: '',
  force_power_points_expended: '',
  tech_power_points_total: '',
  'options-class-selection': '',
  background: 'background',
  alignment: 'alignment',
  experience: 'experiencePoints.current',
  class_resource: '',
  other_resource: '',
  other_resource_name: '',
  other_resource_itemid: '',
  cr: '',
  allies_and_organizations: '',
  age: '',
  size: '',
  height: '',
  character_appearance: '',
  weight: '',
  eyes: '',
  skin: '',
  hair: '',
  rtype: '',
  charname_output: '',
  character_backstory: '',
  tech_operative: '',
  sleight_of_hand_flat: '',
  survival_prof: '',
  advantagetoggle: '',
  cust_powerslots: '',
  piloting_prof: ''
}
